### PR TITLE
index.md

### PR DESCRIPTION
**Pull request by nitisha2017098**
Forked from https://github.com/Mr-codehunter

### CODE REVIEW

**Comment by Mr-codehunter** [comment]
@nitisha2017098 

You are not correct comments for git commits why?

**Review by Mr-codehunter — APPROVED** [review]

**Comment by nitisha2017098** [comment]
On Tue, Feb 14, 2023, 1:09 PM Deepak Kumar ***@***.***> wrote:
>
> @nitisha2017098
Actually, I didn't correct it because I thought I can't be re-committed again .
I will try again, if I have any problem , I will ask.

-- 
Nitisha Kumari
https://github.com/nitisha2017098

**Comment by Mr-codehunter** [comment]
Any updates @nitisha2017098 

--
Mr-codehunter
+91 8847547031

**Comment by nitisha2017098** [comment]
On Thu, 16 Feb 2023 at 00:15, Deepak Kumar ***@***.***> wrote:
>
> Any updates @nitisha2017098
>
Do I need to change the commit, I thought I didn't  need to do it for now
Can you guide me what exactly you want me to do?


-- 
Nitisha Kumari
https://github.com/nitisha2017098

**Pull request merged**
